1. Импортируйте пакет numpy под именем np

In [1]:
import numpy as np

2. Распечатайте версию numpy

In [2]:
print(np.__version__)

1.26.4


3. Создайте вектор со значениями от 10 до 49 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [12]:
A = np.random.random((5,5))
print(A)

[[0.64358985 0.77621004 0.68329018 0.91774474 0.91328176]
 [0.21473351 0.63715337 0.92090262 0.7721383  0.26861897]
 [0.49428744 0.85288126 0.17350766 0.7782993  0.3882513 ]
 [0.8929048  0.81732248 0.71134781 0.1656408  0.91518786]
 [0.08368765 0.15504735 0.43085952 0.99051854 0.85670333]]


array([0.78682331, 0.56270935, 0.53744539, 0.70048075, 0.50336328])

array([0.77621004, 0.63715337, 0.49428744, 0.81732248, 0.43085952])

6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [ ]:
a = np.array([x for x in range(27)])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [40]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [36]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [38]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [42]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [44]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

(array([0, 3, 4], dtype=int64),)


12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [54]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [59]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [65]:
angles = np.array([3.14, 3.14/2, 6.28])

[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [68]:
v = np.random.random(size=[10])
print(v)

[0.30821184 0.13178341 0.88810901 0.51581108 0.87313982 0.79408365
 0.26204075 0.14962622 0.45199466 0.34446024]


[0.13178341 0.14962622 0.26204075 0.30821184 0.34446024 0.45199466
 0.51581108 0.79408365 0.87313982 0.88810901]


16. Проверить, одинаковы ли два NumPy массива

In [71]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

True


17. В одномерном массиве заменить максимальный элемент на ноль

In [73]:
Z = np.random.random(10)

In [74]:
Z

array([0.16782157, 0.13655578, 0.59454878, 0.02957322, 0.81242629,
       0.71645444, 0.48757387, 0.05812814, 0.21499663, 0.24011352])

[0.16782157 0.13655578 0.59454878 0.02957322 0.         0.71645444
 0.48757387 0.05812814 0.21499663 0.24011352]


18. Замените все нечетные числа одномерного массива на -1.

In [76]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [88]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [90]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [93]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])