In [1]:
import numpy as np

In [2]:
vector_row = np.array([1, 2, 3])

In [3]:
vector_row

array([1, 2, 3])

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.random.seed(42)

In [10]:
np.random.random(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [15]:
np.random.randint(0,30,10)

array([11, 29,  5,  1, 27, 20,  0, 11, 25, 21], dtype=int32)

In [17]:
np.random.randn(4, 2)

array([[-1.47632969,  1.48698096],
       [-0.02445518,  0.35555132],
       [ 0.41701111,  0.83246186],
       [-0.29339915, -0.02983857]])