1. Импортируйте пакет numpy под именем np

In [2]:
import numpy as np

2. Распечатайте версию numpy

In [3]:
print(np.__version__)

2.4.6


3. Создайте вектор со значениями от 10 до 49 

In [6]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

In [7]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [94]:
A = np.random.random((5,5))
print(A)

[[0.19550265 0.97267806 0.17987815 0.5174298  0.62283255]
 [0.66339879 0.58119708 0.47984349 0.57070442 0.82058842]
 [0.93869162 0.5174247  0.94856738 0.66123063 0.9588339 ]
 [0.09354843 0.55955816 0.40433033 0.73434474 0.83606706]
 [0.95017199 0.61491763 0.71783851 0.3911007  0.19003745]]


In [95]:
np.mean(A, axis=1)

array([0.49766424, 0.62314644, 0.80494965, 0.52556974, 0.57281326])

array([0.78682331, 0.56270935, 0.53744539, 0.70048075, 0.50336328])

In [96]:
np.median(A, axis=1)

array([0.5174298 , 0.58119708, 0.93869162, 0.55955816, 0.61491763])

array([0.77621004, 0.63715337, 0.49428744, 0.81732248, 0.43085952])

6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [15]:
a = np.array([x for x in range(27)])

In [16]:
print(a.reshape(3, 3, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [101]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

In [102]:
print(a.astype(int))

[[3 1 8]
 [4 7 1]]


[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [98]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

In [99]:
print(a.astype(np.bool_))

[[ True False False]
 [ True  True  True]
 [False False  True]]


[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [33]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

In [36]:
print(np.hstack((a1, a2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [39]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

In [42]:
np.vstack((a1, a2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11]])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [43]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

In [49]:
np.array(np.where(a == b), dtype=np.int32)

array([[0, 3, 4]], dtype=int32)

(array([0, 3, 4], dtype=int64),)


12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [50]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

In [52]:
print(np.dot(a, b))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [53]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

In [54]:
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [56]:
angles = np.array([3.14, 3.14/2, 6.28])

In [58]:
print(np.sin(angles))

[ 0.00159265  0.99999968 -0.0031853 ]


[ 0.00159265  0.99999968 -0.0031853 ]


15. Отсортировать вектор

In [59]:
v = np.random.random(size=[10])
print(v)

[0.89158514 0.47526598 0.95250716 0.659865   0.15071602 0.98704368
 0.41863682 0.11735328 0.7599535  0.51682558]


In [60]:
np.sort(v)

array([0.11735328, 0.15071602, 0.41863682, 0.47526598, 0.51682558,
       0.659865  , 0.7599535 , 0.89158514, 0.95250716, 0.98704368])

[0.13178341 0.14962622 0.26204075 0.30821184 0.34446024 0.45199466
 0.51581108 0.79408365 0.87313982 0.88810901]


16. Проверить, одинаковы ли два NumPy массива

In [61]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [64]:
print(np.array_equal(a, b))

True


True


17. В одномерном массиве заменить максимальный элемент на ноль

In [68]:
Z = np.random.random(10)

In [69]:
Z

array([0.85651605, 0.2672706 , 0.06598982, 0.46685668, 0.6800562 ,
       0.4039565 , 0.49806835, 0.38547958, 0.31665896, 0.2052895 ])

In [71]:
Z[np.argmax(Z)] = 0
print(Z)

[0.         0.2672706  0.06598982 0.46685668 0.6800562  0.4039565
 0.49806835 0.38547958 0.31665896 0.2052895 ]


[0.16782157 0.13655578 0.59454878 0.02957322 0.         0.71645444
 0.48757387 0.05812814 0.21499663 0.24011352]


18. Замените все нечетные числа одномерного массива на -1.

In [78]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [80]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [104]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [105]:
arr[(arr > 30) | (arr < 5)] = 10
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

In [90]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [91]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

In [92]:
a.sort(axis=0)
a

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])